import { BrandConfig } from "@/domains/shared/contracts";

export const brandCatalog: BrandConfig[] = [
  {
    id: "matsuri",
    label: "Matsuri",
    heroTitle: "Rituals that turn brunch into belonging.",
    heroDescription:
      "An airy cafe loyalty world with dessert journeys, soft seasonal rituals, and creator-led social rewards.",
    signatureMood: "Calm editorial social cafe",
    theme: {
      pageGradient: "linear-gradient(180deg, #fff8f2 0%, #f5ede4 100%)",
      heroGradient: "linear-gradient(140deg, #ffe3cf 0%, #f5eee9 55%, #fff 100%)",
      accent: "#d77843",
      accentSoft: "rgba(215, 120, 67, 0.16)",
      text: "#221d19",
      headingFont: "\"IvyMode\", \"Cormorant Garamond\", serif",
      bodyFont: "\"Satoshi\", \"Avenir Next\", sans-serif",
      panel: "rgba(255,255,255,0.8)",
    },
    loops: [
      {
        id: "matsuri-brunch",
        brandId: "matsuri",
        title: "Brunch Bloom",
        description: "Turn repeat late-morning visits into a softly premium routine.",
        target: 5,
        evolvesInto: "matsuri-creator",
      },
      {
        id: "matsuri-creator",
        brandId: "matsuri",
        title: "Creator Ritual",
        description: "Unlock social storytelling rewards after your cafe rhythm is established.",
        target: 3,
      },
    ],
    missions: [
      {
        id: "matsuri-scan",
        brandId: "matsuri",
        title: "First Scan Ceremony",
        description: "Start your Matsuri ritual with a table-side scan.",
        loopId: "matsuri-brunch",
        rewardTitle: "Welcome Matcha Lift",
        rewardValue: "15% off your next dessert order",
        pointsAwarded: 25,
        starsAwarded: 0,
        proofRequired: false,
        approvalRequired: false,
        type: "scan",
        goal: 1,
        heroTag: "Start here",
      },
      {
        id: "matsuri-dessert",
        brandId: "matsuri",
        title: "Dessert Journey",
        description: "Complete a brunch purchase featuring a dessert ritual item.",
        loopId: "matsuri-brunch",
        rewardTitle: "Parfait Privilege",
        rewardValue: "Free signature topping on next parfait",
        pointsAwarded: 40,
        starsAwarded: 2,
        proofRequired: false,
        approvalRequired: true,
        type: "purchase",
        goal: 1,
        heroTag: "Restaurant approval needed",
      },
      {
        id: "matsuri-story",
        brandId: "matsuri",
        title: "Soft Light Story",
        description: "Share your table moment to Instagram and submit proof.",
        loopId: "matsuri-creator",
        rewardTitle: "Creator Cream Reward",
        rewardValue: "Invite-only creator drink upgrade",
        pointsAwarded: 50,
        starsAwarded: 0,
        proofRequired: true,
        approvalRequired: true,
        type: "social",
        goal: 1,
        heroTag: "Proof upload required",
      },
    ],
  },
  {
    id: "roast-theory",
    label: "Roast Theory",
    heroTitle: "Productivity loyalty for people who always come back before 7AM.",
    heroDescription:
      "A sleek coffee identity powered by early-hour streaks, work sessions, and creator-minded loops.",
    signatureMood: "Modern startup cafe energy",
    theme: {
      pageGradient: "linear-gradient(180deg, #eff2f7 0%, #dfe4ee 100%)",
      heroGradient: "linear-gradient(140deg, #272f3d 0%, #40495b 55%, #cbd5e1 100%)",
      accent: "#8c6a41",
      accentSoft: "rgba(140, 106, 65, 0.2)",
      text: "#f9fafb",
      headingFont: "\"Clash Display\", \"Space Grotesk\", sans-serif",
      bodyFont: "\"Satoshi\", \"Avenir Next\", sans-serif",
      panel: "rgba(22, 28, 39, 0.65)",
    },
    loops: [
      {
        id: "roast-morning",
        brandId: "roast-theory",
        title: "7AM Club",
        description: "Build a discipline loop around verified early coffee visits.",
        target: 5,
        evolvesInto: "roast-creator",
      },
      {
        id: "roast-creator",
        brandId: "roast-theory",
        title: "Latte Broadcast",
        description: "Turn focus sessions into social brand advocacy.",
        target: 2,
      },
    ],
    missions: [
      {
        id: "roast-scan",
        brandId: "roast-theory",
        title: "First Desk Check-In",
        description: "Scan into Roast Theory and activate your productivity profile.",
        loopId: "roast-morning",
        rewardTitle: "Focus Fuel Welcome",
        rewardValue: "25 bonus points toward 7AM Club",
        pointsAwarded: 25,
        starsAwarded: 0,
        proofRequired: false,
        approvalRequired: false,
        type: "scan",
        goal: 1,
        heroTag: "Instant activation",
      },
      {
        id: "roast-purchase",
        brandId: "roast-theory",
        title: "Morning Espresso Verified",
        description: "A staff-confirmed purchase earns stars and club progress.",
        loopId: "roast-morning",
        rewardTitle: "Double Shot Bounce",
        rewardValue: "Free extra shot on next visit",
        pointsAwarded: 35,
        starsAwarded: 2,
        proofRequired: false,
        approvalRequired: true,
        type: "purchase",
        goal: 1,
        heroTag: "Validated by staff",
      },
      {
        id: "roast-reel",
        brandId: "roast-theory",
        title: "Latte Art Broadcast",
        description: "Post a quick Reel from your work session and submit it for review.",
        loopId: "roast-creator",
        rewardTitle: "Studio Pour Perk",
        rewardValue: "Priority tasting invite",
        pointsAwarded: 60,
        starsAwarded: 0,
        proofRequired: true,
        approvalRequired: true,
        type: "social",
        goal: 1,
        heroTag: "Approval pending",
      },
    ],
  },
  {
    id: "noir-social",
    label: "Noir Social",
    heroTitle: "VIP nightlife progression with social proof and controlled exclusivity.",
    heroDescription:
      "A luxe resto-bar loyalty world with cocktail circuits, Friday unlocks, group visits, and premium redemption logic.",
    signatureMood: "Neon luxury social energy",
    theme: {
      pageGradient: "linear-gradient(180deg, #110f19 0%, #1d1730 100%)",
      heroGradient: "linear-gradient(140deg, #09030f 0%, #35174e 55%, #f06ca0 100%)",
      accent: "#f06ca0",
      accentSoft: "rgba(240, 108, 160, 0.18)",
      text: "#f8f5ff",
      headingFont: "\"Canela\", \"Cormorant Garamond\", serif",
      bodyFont: "\"Satoshi\", \"Avenir Next\", sans-serif",
      panel: "rgba(20, 14, 36, 0.72)",
    },
    loops: [
      {
        id: "noir-circuit",
        brandId: "noir-social",
        title: "Cocktail Circuit",
        description: "Move through premium nightlife visits and social missions.",
        target: 4,
        evolvesInto: "noir-vip",
      },
      {
        id: "noir-vip",
        brandId: "noir-social",
        title: "VIP Friday Arc",
        description: "A high-intent journey for guests already behaving like regulars.",
        target: 2,
      },
    ],
    missions: [
      {
        id: "noir-scan",
        brandId: "noir-social",
        title: "Velvet Arrival",
        description: "Enter the Noir circuit with your first verified venue scan.",
        loopId: "noir-circuit",
        rewardTitle: "Afterglow Access",
        rewardValue: "Priority table token for your next booking",
        pointsAwarded: 30,
        starsAwarded: 0,
        proofRequired: false,
        approvalRequired: false,
        type: "scan",
        goal: 1,
        heroTag: "Entry unlock",
      },
      {
        id: "noir-group",
        brandId: "noir-social",
        title: "Group Visit Confirmation",
        description: "A host-validated purchase for a group night pushes you deeper into the circuit.",
        loopId: "noir-circuit",
        rewardTitle: "Circuit Sip Reward",
        rewardValue: "Signature cocktail upgrade",
        pointsAwarded: 45,
        starsAwarded: 2,
        proofRequired: false,
        approvalRequired: true,
        type: "purchase",
        goal: 1,
        heroTag: "Host confirmation",
      },
      {
        id: "noir-story",
        brandId: "noir-social",
        title: "Nightline Story",
        description: "Submit your story capture for restaurant confirmation.",
        loopId: "noir-vip",
        rewardTitle: "Velvet Invite",
        rewardValue: "VIP Friday guest-list entry",
        pointsAwarded: 70,
        starsAwarded: 0,
        proofRequired: true,
        approvalRequired: true,
        type: "social",
        goal: 1,
        heroTag: "VIP verification flow",
      },
    ],
  },
];

export function getBrandConfig(brandId: string) {
  return brandCatalog.find((brand) => brand.id === brandId) ?? brandCatalog[0];
}
